services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
      - "18080:18080"
      - "10801:10801"
      - "10802:10802"
      - "10803:10803"
      - "10804:10804"
      - "10805:10805"
      - "10806:10806"
      - "10807:10807"
      - "10808:10808"
      - "10809:10809"
      - "10810:10810"
    volumes:
      - /usr/local/nsx/certs/:/usr/local/nsx/certs/:ro
      - /usr/local/nsx/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /usr/local/nsx/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - /usr/local/nsx/www/:/usr/local/nsx/www/:ro # 网站路径
      - /usr/local/nsx/log/:/usr/local/nsx/log/:rw  #日志文件
      - /usr/local/nsx/nginx/cache/:/var/cache/nginx/:rw # cache
      - /dev/shm/nsx:/dev/shm/nsx
    networks:
      - nsx-network
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    restart: unless-stopped
  xray:
    image: teddysun/xray
    container_name: xray
    volumes:
      - /usr/local/nsx/xray/config.json:/etc/xray/config.json:ro
      - /usr/local/nsx/log/:/usr/local/nsx/log/:rw  #日志文件
      - /usr/local/nsx/certs/:/usr/local/nsx/certs/:ro  #证书文件
      - /dev/shm/nsx:/dev/shm/nsx
    networks:
      - nsx-network
    ports:
      - "10830:10830"
      - "10831:10831"
      - "10832:10832"
      - "10833:10833"
      - "10834:10834"
      - "10835:10835"
      - "10836:10836"
  sing-box:
    image: ghcr.io/sagernet/sing-box
    container_name: sing-box
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"
      - "8086:8086"
      - "8087:8087"
      - "8088:8088"
      - "8089:8089"
      - "8090:8090"
    
    volumes:
      - /usr/local/nsx/sing-box/config.json:/etc/sing-box/config.json:ro
      - /usr/local/nsx/certs/:/usr/local/nsx/certs/:ro # Add certificate mount
      - /usr/local/nsx/log/:/usr/local/nsx/log/:rw   #日志文件
    command: -D /usr/local/nsx/sing-box -C /etc/sing-box/ run
    networks:
      - nsx-network
    restart: unless-stopped
networks:
  nsx-network:
    driver: bridge